In [1]:
G = [0,0,0,0,1,1,1,1]
x = [10,12,13,9,11,14,10,13]
y = [15,17,16,14,18,20,17,19]

In [2]:
#X0Mean, X1 Mean, Y0 Mean, Y1 Mean
totalX0 = sum(x[0:4])
averagex0 = totalX0 / 4
print("X0 =", averagex0)

totalX1 = sum(x[4:8])
averagex1 = totalX1 / 4
print("X1 =", averagex1)

X0 = 11.0
X1 = 12.0


In [3]:
totalY0 = sum(y[0:4])
averagey0 = totalY0 / 4
print("Y0 =", averagey0)

totalY1 = sum(y[4:8])
averagey1 = totalY1 / 4
print("Y1 =", averagey1)

Y0 = 15.5
Y1 = 18.5


In [4]:
#Variability
x_mean = sum(x) / len(x)

y_mean = sum(y) / len(y)

print('xmean = ', x_mean)
print('ymean = ',y_mean)

xmean =  11.5
ymean =  17.0


In [5]:
x_minus_x_mean = [i - x_mean for i in x]
x_minus_xmean_sq2 = [(i - x_mean)**2 for i in x]

total_x_minus_xmean_sq2 = sum(x_minus_xmean_sq2)

print("(xi - xmean) =", x_minus_x_mean)
print("(xi - xmean)^2 =", x_minus_xmean_sq2)
print("Sum =", total_x_minus_xmean_sq2)

(xi - xmean) = [-1.5, 0.5, 1.5, -2.5, -0.5, 2.5, -1.5, 1.5]
(xi - xmean)^2 = [2.25, 0.25, 2.25, 6.25, 0.25, 6.25, 2.25, 2.25]
Sum = 22.0


In [6]:
y_minus_y_mean = [i - y_mean for i in y]
y_minus_ymean_sq2 = [(i - y_mean)**2 for i in y]

total_y_minus_ymean_sq2 = sum(y_minus_ymean_sq2)

print("(yi - ymean) =", y_minus_y_mean)
print("(yi - ymean)^2 =", y_minus_ymean_sq2)
print("Sum =", total_y_minus_ymean_sq2)

(yi - ymean) = [-2.0, 0.0, -1.0, -3.0, 1.0, 3.0, 0.0, 2.0]
(yi - ymean)^2 = [4.0, 0.0, 1.0, 9.0, 1.0, 9.0, 0.0, 4.0]
Sum = 28.0


In [7]:
#(xi-xmean)(yi-ymean)
product = [(xi - x_mean) * (yi - y_mean) for (xi, yi) in zip(x, y)]

print("Products =", product)
sum_product = sum(product)
print("Sum of products =", sum_product)

Products = [3.0, 0.0, -1.5, 7.5, -0.5, 7.5, -0.0, 3.0]
Sum of products = 19.0


In [8]:
#Calculating β₀, βG, and βX
import numpy as np
X = np.column_stack((np.ones(len(G)), G, x))

print("Design Matrix X =\n", X)

# ---------------------------
# 2. Compute Beta = (X'X)^(-1) X'y
# ---------------------------

Xt = X.T
XtX = Xt @ X
XtX_inv = np.linalg.inv(XtX)
Xty = Xt @ y
beta = XtX_inv @ Xty

print("\n(X'X):\n", XtX)
print("\nInverse (X'X)^(-1):\n", XtX_inv)
print("\nX'y:\n", Xty)
print("\nBeta coefficients [β0, βG, βX]:\n", beta)

# Naming them clearly
beta0 = beta[0]
betaG = beta[1]
betaX = beta[2]

print(f"\nβ0  = {beta0:.2f}")
print(f"βG  = {betaG:.2f}")
print(f"βX  = {betaX:.2f}")

Design Matrix X =
 [[ 1.  0. 10.]
 [ 1.  0. 12.]
 [ 1.  0. 13.]
 [ 1.  0.  9.]
 [ 1.  1. 11.]
 [ 1.  1. 14.]
 [ 1.  1. 10.]
 [ 1.  1. 13.]]

(X'X):
 [[   8.    4.   92.]
 [   4.    4.   48.]
 [  92.   48. 1080.]]

Inverse (X'X)^(-1):
 [[ 6.3   0.3  -0.55]
 [ 0.3   0.55 -0.05]
 [-0.55 -0.05  0.05]]

X'y:
 [ 136.   74. 1583.]

Beta coefficients [β0, βG, βX]:
 [8.35 2.35 0.65]

β0  = 8.35
βG  = 2.35
βX  = 0.65


In [9]:
#Variability of ANCOVA vs Variability of Covariance only Model


#Variability for reduced covariance only model
# g = β0 + βX x X

Sxx = total_x_minus_xmean_sq2
Sxy = sum_product
βx = Sxy/Sxx
βo = y_mean - βx * x_mean
print("Sum of squares for X:",Sxx)
print("Sum of Cross-Products of X and Y:",Sxy)
print(f"βx:{βx:.2f}")
print(f"βo:{βo:.2f}")

Sum of squares for X: 22.0
Sum of Cross-Products of X and Y: 19.0
βx:0.86
βo:7.07


In [10]:
#SSE_residuals
beta_x_reduced = βx
beta_0_reduced = βo


y_hat_reduced = [βo + βx * xi for xi in x]

residuals_reduced = [yi - yhi for yi, yhi in zip(y, y_hat_reduced)]
SSE_reduced = sum([r**2 for r in residuals_reduced])

print(f"SSE Reduced Model = {SSE_reduced:.2f}")


SSE Reduced Model = 11.59


In [11]:
#SSE_Ancova
y_hat_full = [beta0 + betaG * Gi + betaX * xi 
              for Gi, xi in zip(G, x)]

residuals_full = [yi - yhi for yi, yhi in zip(y, y_hat_full)]
SSE_ANCOVA = sum([r**2 for r in residuals_full])

print(f"SSE ANCOVA Model = {SSE_ANCOVA:.2f}")


SSE ANCOVA Model = 1.55


In [12]:
#Explained Variability SST of reduced Model
SSR_residual = total_y_minus_ymean_sq2 - SSE_reduced
print(f"SSR_residual = {SSR_residual:.2f}")

SSR_residual = 16.41


In [13]:
#Explained Variability of Full Model
SSR_Full = total_y_minus_ymean_sq2 - SSE_ANCOVA
print(f"SSR_Full = {SSR_Full:.2f}")

SSR_Full = 26.45


In [14]:
#Extra information explained by adding group variable
SSR_G_given_x = SSR_Full - SSR_residual
print(f"SSR_G|x = {SSR_G_given_x:.2f}")

SSR_G|x = 10.04


In [15]:
#F_statistic
parameters_of_ancova = 3
num_groups = len(set(G))
print("Number of groups =", num_groups)
Degree_of_group = num_groups - 1
Degree_of_freedom = len(x) - parameters_of_ancova

F_Statistic = (SSR_G_given_x / Degree_of_group) / (SSE_ANCOVA / Degree_of_freedom)
print(f"F_Statistic = {F_Statistic:.2f}")

Number of groups = 2
F_Statistic = 32.39


In [16]:
#F(1,5) = 32
#Look at F(1,5) in the F_Statistic Table at α = 0.05
#At F(1,5) at α = 0.05 = 6.61

#Therefore, if F_Calculated_Value > F_Theoritical_Value then Ho is rejected and Group information is significant

F_Calculated_Value = F_Statistic
F_Theoretical = 6.61  # Value from F-table

if F_Calculated_Value > F_Theoretical:
    print(f"H0 is rejected because {F_Calculated_Value:.2f} > {F_Theoretical}. \nThe group information is significant.")
else:
    print("H0 is not rejected.\nThe group information is NOT significant.")


H0 is rejected because 32.39 > 6.61. 
The group information is significant.
